system:
    default:
        yui:
            modules:
                # use your prefix, not "ez-"
                ezconf-listapplugin: # should match the first parameter of YUI.add
                    requires: ['ez-pluginregistry', 'plugin', 'base', 'ezconf-listview', 'ezconf-listviewservice'] # depends on the plugin code
                    dependencyOf: ['ez-platformuiapp']
                    path: %extending_platformui.public_dir%/js/apps/plugins/ezconf-listappplugin.js
                ezconf-navigationplugin:
                    requires: ['ez-pluginregistry', 'ez-viewservicebaseplugin', 'ez-navigationitemview']
                    dependencyOf: ['ez-navigationhubviewservice']
                    path: %extending_platformui.public_dir%/js/views/services/plugins/ezconf-navigationplugin.js
                ezconf-listviewservice:
                    requires: ['ez-serversideviewservice']
                    path: %extending_platformui.public_dir%/js/views/services/ezconf-listviewservice.js
                ezconf-listview:
                    requires: ['ez-serversideview']
                    path: %extending_platformui.public_dir%/js/views/ezconf-listview.js
