system:
    default:
        yui:
            modules:
                # use your prefix, not "ez-"
                ezconf-listapplugin: # should match the first parameter of YUI.add
                    requires: ['ez-pluginregistry', 'plugin', 'base'] # depends on the plugin code
                    dependencyOf: ['ez-platformuiapp']
                    path: %extending_platformui.public_dir%/js/apps/plugins/ezconf-listappplugin.js
